### ISSUE TITLE
找不到下载按钮

### ISSUE THREAD

**Issue by rothleer** [fumiama/copymanga#1]
在“个人”界面可以看到下载按钮，但是无法在漫画区找到下载按钮，请问要如何启用？

**Comment by fumiama** [comment]
感谢提醒，刚刚才发现官方又恢复了h5页面，可能因为与之前略有不同导致无法出现下载按钮。会在近期维护一个版本解决此问题。

**Comment by fumiama** [comment]
已解决，请看最新`release`
