### ISSUE TITLE
APP版章节API返回为空

### ISSUE THREAD

**Issue by Xdq1015** [fumiama/copymanga#13]
APP版无限闪退,debug了一下,发现原因是章节list返回永远为空导致下标溢出,我自己也试了一下好像这个api确实有点问题...

**Comment by fumiama** [comment]
是那边改api了，有空重新适配一下看看。他这个吃相挺难看的，加一堆广告，明明自己也没版权，还给tachiyomi的插件放鬼图搞防盗，导致tachiyomi也用不成了，大妈之家比它良心一百倍。

**Comment by Xdq1015** [comment]
> 是那边改api了，有空重新适配一下看看。他这个吃相挺难看的，加一堆广告，明明自己也没版权，还给tachiyomi的插件放鬼图搞防盗，导致tachiyomi也用不成了，大妈之家比它良心一百倍。

大妈之家以前确实好用，可惜现在因为版权原因漫画太少了

**Comment by fumiama** [comment]
大部分被隐藏了，没有真的消失，但是一则被隐藏之后很难继续更新，所以只能用于看早就完结的老漫，二则相对新的漫画，即使是被隐藏的，也大多打了各种圣光，观感不如去其他漫画站找原版。

**Comment by fumiama** [comment]
最新版已解决
