### ISSUE TITLE
有可能提供ios版本吗

### ISSUE THREAD

**Issue by alphavvv** [fumiama/copymanga#15]
请问有可能提供ios版本吗

**Comment by fumiama** [comment]
建议了解：[安卓程序能安装在IOS吗？](https://www.baidu.com/s?ie=UTF-8&wd=%E5%AE%89%E5%8D%93%E7%A8%8B%E5%BA%8F%E8%83%BD%E5%AE%89%E8%A3%85%E5%9C%A8IOS%E5%90%97%EF%BC%9F)
