### ISSUE TITLE
能分享一下api吗

### ISSUE THREAD

**Issue by Minori-ty** [fumiama/copymanga#2]

**Comment by BurstLinker996** [comment]
sourcegraph上面搜出来的。
[app/src/main/res/values/strings.xml](https://github.com/fumiama/copymanga/blob/main/app/src/main/res/values/strings.xml)
![image](https://user-images.githubusercontent.com/16608185/124117192-65a80780-daa2-11eb-86b8-53639fb082a3.png)

**Comment by Minori-ty** [comment]
感谢

**Comment by fumiama** [comment]
api抓包就可以得到，我的源码也有，不过由于还没开发完，目前不太完全。
