### ISSUE TITLE
大佬这个项目要怎么用哇

### ISSUE THREAD

**Issue by lightkunwo** [fumiama/copymanga#32]
直接把全部代码文件下载到手机里吗

**Comment by fumiama** [comment]
安装包会安吧 https://github.com/fumiama/copymanga/releases

**Comment by lightkunwo** [comment]
好的好的，谢谢大佬


与君约定，四月给我冲啊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fumiama/copymanga"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月19日(星期四) 晚上10:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fumiama/copymanga] 大佬这个项目要怎么用哇 (Issue #32)





 
安装包会安吧 https://github.com/fumiama/copymanga/releases
