### ISSUE TITLE
带有多版本目录的漫画选择章节时会偏移

### ISSUE THREAD

**Issue by maudslice** [fumiama/copymanga#33]
版本: v2.0.beta21
设备: huawei P30
如何复现: 见gif
![截图_20231024091844](https://github.com/fumiama/copymanga/assets/52091023/6e33ebb6-577f-4f84-bb7b-a379b714de51)

**Comment by fumiama** [comment]
我也发现了，下版修复。

**Comment by fumiama** [comment]
目前可以通过进入下载后长按某章节按钮进入阅读临时解决。
