### ISSUE TITLE
关于下载

### ISSUE THREAD

**Issue by wqc7741** [fumiama/copymanga#34]
浏览过的漫画都会出现在下载，这个是特色，还是bug？
另，今天点击分类第一个碧蓝的漫画后，出现闪退，重复几次皆如此。
手机是红米k60u，安卓13

**Comment by fumiama** [comment]
> 浏览过的漫画都会出现在下载

是特色，后续增加过滤0MB漫画功能，即可筛选掉没有实际下载的漫画。

> 今天点击分类第一个碧蓝的漫画后，出现闪退，重复几次皆如此

真的诶，我看看。

**Comment by fumiama** [comment]
那本闪退的书不讲武德，前后数据不一致（
影响范围应该不大，总之先修复了，和下版本一起发布。

**Comment by fumiama** [comment]
fixed in v2.0.2
