### ISSUE TITLE
音量翻页在横向模式下无效

### ISSUE THREAD

**Issue by xiaohuo-desu** [fumiama/copymanga#35]
**环境**
测试环境是Android Studio中的Pixel 3a
版本为最新：v2.0.3

**问题**
在横向模式下使用音量翻页功能失效，在竖直模式下正常

**复现**
在设置中开启翻页，默认横向模式下进入漫画，使用音量键，无效
调整为竖直模式，退出漫画，进入漫画后使用音量键，正常工作

**DEBUG**
测试时发现以竖直模式下进入漫画后退出时，PagesManager是有值的
![image](https://github.com/fumiama/copymanga/assets/49596040/7e5f327e-b167-4ec5-85f2-5859053716e0)
但是以横向模式进入后，点击音量键和退出时，PagesManager均是空值
![image](https://github.com/fumiama/copymanga/assets/49596040/5d041115-855c-44b6-9055-70d43e5ef93c)

**PR意向**
不熟悉安卓与Kotlin，所以不确定其之间的联系，也无法提供PR

**Comment by fumiama** [comment]
感谢发现问题，下版修复。
