### ISSUE TITLE
下载下漏的问题

### ISSUE THREAD

**Issue by maixxx987** [fumiama/copymanga#38]
同时下载多部漫画的时候，可能会存在部分漫画下漏的情况；

比如说同时下载三部漫画A，B，C； 其中A可能完整下载了，但B中的某几话可能下漏了几页；具体阅读这几话的时候，缺失的这几页也不会展示出来，进度条上的总页数也是错误的

**Comment by fumiama** [comment]
目前没有做同时下载多部漫画，请在一个下载页亮屏等待全部漫画下载完成后再离开。

**Comment by maixxx987** [comment]
好的
