### ISSUE TITLE
顶部通知栏遮挡搜索框

### ISSUE THREAD

**Issue by rxw22** [fumiama/copymanga#40]
![S31215-20075658_top.fumiama.copymanga.png](https://github.com/fumiama/copymanga/assets/75081273/98f65c66-4c61-4376-ada7-e9e865769b81)

![S31215-20080323_top.fumiama.copymanga.png](https://github.com/fumiama/copymanga/assets/75081273/e4cc7718-22de-48c1-a76e-7b34f2587000)

Android 13
机型魅族17，最新发布版的apk

**Comment by fumiama** [comment]
下面这个正常的呢？

**Comment by rxw22** [comment]
> 下面这个正常的呢？

下面这个是刚启动App，没有滑动的情况，这个时候是正常的，向上滑动后，搜索框就被状态栏遮挡了。

**Comment by fumiama** [comment]
OK, 下版本修复。

**Comment by rxw22** [comment]
> OK, 下版本修复。

辛苦大佬
