### ISSUE TITLE
下载页面多选模式下选择一定数量以上点击下载闪退

### ISSUE THREAD

**Issue by Nanonanooo** [fumiama/copymanga#42]
机型：Sony Xperia XZ Premium (G8142)
系统：LineageOS 20 (Android 13)
版本：2.0.5

在下载页面启用多选模式，选了大概10话点击下载，会闪退，并且重启app后选择的项目显示已下载，点击则报错zip图片数量统计错误。
运行`db logcat -v time *:E > crash_log.log`得到日志如下：
[crash_log.log](https://github.com/fumiama/copymanga/files/13714331/crash_log.log)

（同时吐槽一下没看懂这个下载页面的操作逻辑，感觉就和普通文件管理器一样就行，而且我的屏幕16：9一开始都没看到下载按钮，文件存储路径也建议贴在设置或者什么地方）

**Comment by fumiama** [comment]
这应该是网络原因，尝试更换网络环境/减少下载个数。另外，下载无需启用多选模式，多选模式是用于批量删除已下载章节。

> 吐槽一下没看懂这个下载页面的操作逻辑，感觉就和普通文件管理器一样就行

文件管理器式样显示效率太低。

> 而且我的屏幕16：9一开始都没看到下载按钮

不管什么屏幕都会被折叠在下面，这是加了顶栏导致的，如果你用过我写的动漫之家Lite可以对比一下。

> 文件存储路径也建议贴在设置或者什么地方

可以在下载页加一个点击直达文件夹。

**Comment by fumiama** [comment]
> 可以在下载页加一个点击直达文件夹。

在现今的安卓系统上几乎无法实现，因此放弃。
