### ISSUE TITLE
安装提示有病毒

### ISSUE THREAD

**Issue by chengchp** [fumiama/copymanga#44]
如题呀  手机一加11

**Comment by fumiama** [comment]
没课保护费导致的，对此我是一点办法没有。你可以选择不安装，或者去网络上搜索绕过方法。

**Comment by ogios** [comment]
我一加ace3v也是报毒，可以用但是打开一些app老有提示，甚至某些app因为拷贝漫画报毒无法打开😂
老哥你那可以吗
