### ISSUE TITLE
「加入书架」返回空回应

### ISSUE THREAD

**Issue by HeRaNO** [fumiama/copymanga#55]
使用 2.1.1 版本，登录状态下无法将漫画添加到书架，提示「空回应」

![Screenshot_2024-03-07-14-28-07-345_top fumiama co](https://github.com/fumiama/copymanga/assets/18643142/38284b75-d329-4a5b-b83a-1d2448d5d2b8)

**Comment by fumiama** [comment]
无法复现。在官方APP一切正常吗？

**Comment by HeRaNO** [comment]
> 无法复现。在官方APP一切正常吗？

是的，官方最新的 v2.1.7 上能加入

**Comment by HeRaNO** [comment]
在最新的 2.1.3 版本仍然空响应 :(

**Comment by fumiama** [comment]
因为我没办法复现，所以没法修呀，你要是着急的话可以qq私发我账号密码做测试。

**Comment by HeRaNO** [comment]
抓了一下包，感觉是我手机上的网络问题，因为超时了返回了空响应
