### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by Laomu-MagicFlute** [fumiama/copymanga#61]
提升升级到最新版APP
![Screenshot_2024-04-01-12-22-19-199_top fumiama copymanga](https://github.com/fumiama/copymanga/assets/111882303/4831ee82-c951-4fef-83e3-f7d3036dac94)

**Comment by Laomu-MagicFlute** [comment]
用的是2.7.7

**Comment by fumiama** [comment]
应该是官方改了登录逻辑。

**Comment by TNT569** [comment]
目前2.7.7版本也无法加载详情界面![Uploading Screenshot_2024-04-01-13-01-11-809_top.fumiama.copymanga.jpg…]()

**Comment by Laomu-MagicFlute** [comment]
改了api地址，漫画可以正常看
但是登录不上，会跳出页面返回到菜单栏
