### ISSUE TITLE
漫画集数变动闪退

### ISSUE THREAD

**Issue by zxczaq001** [fumiama/copymanga#62]
![image](https://github.com/fumiama/copymanga/assets/104310573/36ee4d60-34f5-41c4-a115-cf83a07a91a7)
![image](https://github.com/fumiama/copymanga/assets/104310573/2175317b-6fea-497b-bae2-bbc7cd2e1116)
原来已经更新75 我在app看完了 之后拷贝删除了75话 app显示有更新点进去闪退

**Comment by fumiama** [comment]
无法复现。
