### ISSUE TITLE
能请教一下你是怎么抓拷贝漫画app的接口的吗？

### ISSUE THREAD

**Issue by Minori-ty** [fumiama/copymanga#73]
我用fiddler抓，信任CA证书，开启代理后，老是显示断开网络，SSL握手失败

**Comment by Minori-ty** [comment]
> 抓安卓端，用http canary。

就是抓安卓端，用http canary，一点进去，就显示断开网络

**Comment by fumiama** [comment]
你不是fiddler吗

**Comment by Minori-ty** [comment]
> 你不是fiddler吗

也有用http canary和reqable试了一下，都不行

**Comment by Minori-ty** [comment]
我是真机抓包，手机没有root，信任了CA证书，不过是用户证书。点进去的时候，显示断网，无法抓包。所以想请教一下你是怎么抓包的

**Comment by fumiama** [comment]
要root。

**Comment by Minori-ty** [comment]
> 要root。

我现在是用雷电9 root了，还是不行。是需要安装move certificates模块，移动用户证书到系统吗？

**Comment by fumiama** [comment]
咋这么困难，HTTP Canary启动默认有个引导，做一遍就能用了。

**Comment by Minori-ty** [comment]
> 咋这么困难，HTTP Canary启动默认有个引导，做一遍就能用了。

感谢回复。我在网上找了好几个HTTP Canary，都不行。后面找到了一个旧版的HTTP Canary，引导做一遍就可以了，原来是新版的不行，要旧版的才可以。

https://github.com/lusimei/HttpCanary

**Comment by fumiama** [comment]
怪耶
