### ISSUE TITLE
在2.3.3版本无法登录

### ISSUE THREAD

**Issue by show-me-code** [fumiama/copymanga#74]
作者大大你好
我在2.3.3版本登录，出现“请更新到最新的app版本”，之后无法登录

**Comment by fumiama** [comment]
设置中更改拷贝版本号为`2.2.0`。

**Comment by ANGJustinl** [comment]
现在需要更改拷贝版本号为2.2.1+

**Comment by ryougishiki1999** [comment]
> 现在需要更改拷贝版本号为2.2.1+

![Screenshot_2024-06-01-23-14-52-594_top.fumiama.copymanga.jpg](https://github.com/fumiama/copymanga/assets/43427057/f9f8fd92-e0c3-4a45-9979-cd96e81206d3)

更改为2.2.1 仍然无法登录且无法浏览任何内容
点进任何漫画都一直在加载

![Screenshot_2024-06-01-23-16-44-691_top.fumiama.copymanga.jpg](https://github.com/fumiama/copymanga/assets/43427057/f43416a0-07b2-450f-9503-ae7d3e3eb5b5)

**Comment by ANGJustinl** [comment]
你提示更新版本了吗,没提示就是版本正确罢,如果这样你在排除一下别的？

**Comment by ryougishiki1999** [comment]
> 你提示更新版本了吗,没提示就是版本正确罢,如果这样你在排除一下别的？

![Screenshot_2024-06-01-23-30-07-030_top.fumiama.copymanga-edit.jpg](https://github.com/fumiama/copymanga/assets/43427057/5e0f9808-04f5-44d3-9f2e-c9bc06316aa4)

提示需要更新

**Comment by ANGJustinl** [comment]
不知道,我好像2.1.9也能进,你再试试别的版本号？

**Comment by Abraxas730** [comment]
出现了同样的问题，两个设备上试了上面提及的所有版本号，都提示需要更新。

**Comment by Abraxas730** [comment]
> 出现了同样的问题，两个设备上试了上面提及的所有版本号，都提示需要更新。

不好意思，卸载重启手机并重装就登录成功了。版本号更改成2.2.1即可。

**Comment by MKIII-Londoner** [comment]
遇到了同样的问题，卸载重启重装后问题依然存在，安装旧版未解决，更改版本号直到改成2.3.3才解决。

**Comment by LFT135** [comment]
大佬牛逼

**Comment by balab66** [comment]
改成2.2.1不行但是改成2.3.3就可以了，谢谢大佬

**Comment by Floice** [comment]
今天2.3.4可以

**Comment by wtfsb19** [comment]
2.3.4也登陆不了，提示更新

**Comment by LFT135** [comment]
> 2.3.4也登陆不了，提示更新

你软件版本是多少设置里就填多少

**Comment by wtfsb19** [comment]
> > 2.3.4也登陆不了，提示更新
> 
> 你软件版本是多少设置里就填多少

感谢，确实好了。我刚刚也试过这个版本号但还是提示更新，不知道为什么又行了

**Comment by 148278001** [comment]
从2.1.7试到2.3.6了都没成功，软件版本是最新的2.3.3

**Comment by LFT135** [comment]
> 从2.1.7试到2.3.6了都没成功，软件版本是最新的2.3.3

设置完重启

**Comment by 148278001** [comment]
> > 从2.1.7试到2.3.6了都没成功，软件版本是最新的2.3.3
> 
> 设置完重启

感谢，成功了
