### ISSUE TITLE
登录功能异常

### ISSUE THREAD

**Issue by xz108** [fumiama/copymanga#77]
已经是最新版本显示仍需更新
![Screenshot_2024-06-05-11-13-14-374_top fumiama copymanga](https://github.com/fumiama/copymanga/assets/55474362/e9115239-df9a-4515-9a04-10f50318c4bb)

**Comment by Shimo0122** [comment]
拷贝版本过低，改为2.2.1以上。改后重开软件即可

**Comment by xz108** [comment]
在设置里更改了拷贝版本号解决了
