### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by winter527** [fumiama/copymanga#78]
作者大大，你好。目前我是最新版本，并且拷贝漫画版本也调至2.2.1，但是仍然无法登陆。以下照片是输入账号密码后的情况：
![e221e05bdf6cace2e779291e81722dd2](https://github.com/fumiama/copymanga/assets/143273136/8a61bb1c-6def-4d98-a246-a0f33b8430fb)
![2685f5eebc19d82e3a655d9cdc510d0a](https://github.com/fumiama/copymanga/assets/143273136/bce640cc-a751-4088-9a76-a4311cc12c04)

**Comment by Sagitajn** [comment]
我也遇到了同样的问题，我目前版本是v2.3.3，它需要我更新到最新版本，可是我已经更新了

**Comment by Sagitajn** [comment]
> 我也遇到了同样的问题，我目前版本是v2.3.3，它需要我更新到最新版本，可是我已经更新了

不知道怎么解释，我重装了一下又好了，现在可以登陆了....

**Comment by jiamei11** [comment]
设置里改完2.2.1后 清除软件的缓存 就能登录了

**Comment by balab66** [comment]
> 设置里改完2.2.1后 清除软件的缓存 就能登录了

我这边还是不行，改了2.2.1提示我更新，然后更新到2.3.3又是不能登录

**Comment by MKIII-Londoner** [comment]
> > 设置里改完2.2.1后 清除软件的缓存 就能登录了
> 
> 我这边还是不行，改了2.2.1提示我更新，然后更新到2.3.3又是不能登录

试过改成2.3.3了吗？

**Comment by balab66** [comment]
> > > 设置里改完2.2.1后 清除软件的缓存 就能登录了
> > 
> > 
> > 我这边还是不行，改了2.2.1提示我更新，然后更新到2.3.3又是不能登录
> 
> 试过改成2.3.3了吗？

我的话是重新下载了一个2.2.1，然后提示我更新到2.3.3，然后登录界面还是提示我请更新到最新版本

**Comment by balab66** [comment]
> > > 设置里改完2.2.1后 清除软件的缓存 就能登录了
> > 
> > 
> > 我这边还是不行，改了2.2.1提示我更新，然后更新到2.3.3又是不能登录
> 
> 试过改成2.3.3了吗？

对了我下载的不只是登录不上的问题，其他界面也卡在加载读条，完全加载不出来

**Comment by Sagitajn** [comment]
> > > > 设置里改完2.2.1后 清除软件的缓存 就能登录了
> > > 
> > > 
> > > 我这边还是不行，改了2.2.1提示我更新，然后更新到2.3.3又是不能登录
> > 
> > 
> > 试过改成2.3.3了吗？
> 
> 对了我下载的不只是登录不上的问题，其他界面也卡在加载读条，完全加载不出来

我跟你是一样的，所有的页面都加载不出来，搜索也用不了，只能打开自己的历史下载，我直接清除缓存卸载重装了

**Comment by Sagitajn** [comment]
> > > > > 设置里改完2.2.1后 清除软件的缓存 就能登录了
> > > > 
> > > > 
> > > > 我这边还是不行，改了2.2.1提示我更新，然后更新到2.3.3又是不能登录
> > > 
> > > 
> > > 试过改成2.3.3了吗？
> > 
> > 
> > 对了我下载的不只是登录不上的问题，其他界面也卡在加载读条，完全加载不出来
> 
> 我跟你是一样的，所有的页面都加载不出来，搜索也用不了，只能打开自己的历史下载，我直接清除缓存卸载重装了

但是我重装是直接装了2.3.3

**Comment by MKIII-Londoner** [comment]
> > > > 设置里改完2.2.1后 清除软件的缓存 就能登录了
> > > 
> > > 
> > > 我这边还是不行，改了2.2.1提示我更新，然后更新到2.3.3又是不能登录
> > 
> > 
> > 试过改成2.3.3了吗？
> 
> 对了我下载的不只是登录不上的问题，其他界面也卡在加载读条，完全加载不出来

我之前也遇到过，试了其他人的方法没能解决，我是在新装了2.3.3之后再在设置里把版本号改成2.3.3才解决的问题

**Comment by balab66** [comment]
> > > > > 设置里改完2.2.1后 清除软件的缓存 就能登录了
> > > > 
> > > > 
> > > > 我这边还是不行，改了2.2.1提示我更新，然后更新到2.3.3又是不能登录
> > > 
> > > 
> > > 试过改成2.3.3了吗？
> > 
> > 
> > 对了我下载的不只是登录不上的问题，其他界面也卡在加载读条，完全加载不出来
> 
> 我之前也遇到过，试了其他人的方法没能解决，我是在新装了2.3.3之后再在设置里把版本号改成2.3.3才解决的问题

你是怎么改的版本号a

**Comment by fumiama** [comment]
与 #77 重复。
