### ISSUE TITLE
作者大大，有考虑iOS版吗？

### ISSUE THREAD

**Issue by bbuus** [fumiama/copymanga#90]

**Comment by fumiama** [comment]
没有可能，首先，iOS和安卓的开发路径完全不一样，要开发的话就要从头来一遍了。其次，iOS的开发者每年要给苹果交100美元的费用，要不然的话开发出来的软件一般用户安装极为繁琐，即使费劲装上之后也只能用7天，过期就要重新签名，这用户体验基本上没救了。如果想要上架商店，那就会被各种审核，众所周知，拷贝本身就没版权，这就基本上就断绝了这种游走在灰色地带的漫画软件在iOS开发的可能性。
