### ISSUE TITLE
部分漫画无法打开

### ISSUE THREAD

**Issue by twtan** [fumiama/copymanga#93]
一部分漫画无法打开，一部分漫画正常
![Screenshot_2024-09-30-23-39-29-481_top fumiama co](https://github.com/user-attachments/assets/4e39ab31-86c7-4ada-a1fd-97a6a3eee446)

不能打开的漫画一直卡在这个界面
目前发现几个打不开的漫画的共同点是目录都是两百话以上的漫画 
比如下面2个漫画
屎作猎人向神作发起挑战，独自一人的异世界攻略
我试过自己开代理服务器也没法打开

**Comment by Traveller23** [comment]
我也遇到了这个问题, 也是有两个比较长篇的漫画打不开了.
一个是 "天国大魔境", 另一个是 "葬送的芙莉莲".

**Comment by yuduotianguang** [comment]
这是拷贝下架的漫画，当然无法打开

**Comment by Traveller23** [comment]
哦哦, 那最近下架了很多啊, 明白了.

**Comment by fumiama** [comment]
有可能只是前台做了屏蔽。

**Comment by NNSEARDNN** [comment]
今天我也遇到这个问题，有的漫画能打开有的漫画进去页数加载不进去，但是换到官方的app就能看

**Comment by fumiama** [comment]
> 今天我也遇到这个问题，有的漫画能打开有的漫画进去页数加载不进去，但是换到官方的app就能看

可以给出具体的漫画以便测试。

**Comment by NNSEARDNN** [comment]
非常抱歉作者，我提供了看起来可能是错误的信息，事情是这样，昨天下午打开软件挂上vpn后随便打开一个漫画，都能看到漫画的简介信息，但是进去阅读后，大部分的漫画进入后都显示重新加载，只有小部分漫画能够显示图片，我检查了我的代理可以正常访问网络并更换了节点，但是在当时问题依旧存在，今天我重新查看时现在问题似乎已经不在了，不再出现无法加载图片的情况。如有打扰，请见谅。

**Comment by fumiama** [comment]
没事。
