### ISSUE TITLE
下载页面底部下载按钮遮挡部分漫画话数和虚拟按键

### ISSUE THREAD

**Issue by ArkhalisDragon** [fumiama/copymanga#96]
如图，弹窗式的下载按钮会挡住最下面几话，且和虚拟按键有一定重叠，导致操作略有不便

![Screenshot_2024-10-17-13-38-24-492_top fumiama copymanga](https://github.com/user-attachments/assets/deb80f18-9291-4bbe-b1c8-fb78c1b5cc50)

**Comment by fumiama** [comment]
列表滚动到中间部分松手的时候，下载栏会自动隐藏到旁边。

**Comment by fumiama** [comment]
虚拟按钮确实需要注意一下。

**Comment by ArkhalisDragon** [comment]
> 列表滚动到中间部分松手的时候，下载栏会自动隐藏到旁边。

滚动到底部的时候会挡住最后一行的几话，很难点，而且会看不到下载进度（
