### ISSUE TITLE
打开特定漫画时闪退

### ISSUE THREAD

**Issue by HeRaNO** [fumiama/copymanga#97]
软件版本：2.3.5（设置拷贝版本号：2.2.3）

打开漫画「影宅」时会闪退，直接点击 p1，然后 p2

| p1 | p2 |
|:--:|:--:|
| ![Screenshot_2024-10-19-13-27-21-365_top fumiama co](https://github.com/user-attachments/assets/2ab2bc12-0832-4ea6-b14e-b2f2761fd10b) | ![Screenshot_2024-10-19-13-26-02-423_com miui third](https://github.com/user-attachments/assets/57c54d1e-acbd-4ba8-aaa1-b4a902e072e1) |

红米 K70 上可以稳定复现

**Comment by fumiama** [comment]
无法复现。请安装测试版本[app-debug.apk.zip](https://github.com/user-attachments/files/17443211/app-debug.apk.zip)并在此处贴出报错信息。

**Comment by HeRaNO** [comment]
![Screenshot_2024-10-19-14-47-16-336_com miui third](https://github.com/user-attachments/assets/ab052b23-fa49-43d0-b8c7-f3785e6b29b2)
![Screenshot_2024-10-19-14-47-25-938_com miui third](https://github.com/user-attachments/assets/23c6a0f2-87ab-4546-8131-50c60fd9aac9)
![Screenshot_2024-10-19-14-47-30-710_com miui third](https://github.com/user-attachments/assets/66ec332b-f7bc-4df3-a117-7259be669cc0)

**Comment by fumiama** [comment]
已定位问题，尝试此版本看是否修复：
[app-debug.apk.zip](https://github.com/user-attachments/files/17443819/app-debug.apk.zip)

**Comment by HeRaNO** [comment]
> 已定位问题，尝试此版本看是否修复： [app-debug.apk.zip](https://github.com/user-attachments/files/17443819/app-debug.apk.zip)

这个版本可以修复问题，谢谢！
